config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "songs#index"

  resources :songs
  resource :search, only: :show
  resource :contact_us, only: :create do
    get "/", action: :new
  end
end

app/models/contact_us_form.rb
class ContactUsForm
  include ActiveModel::Model

  attr_accessor :full_name, :email, :phone_number, :text, :user

  validates :full_name, :email, :text, presence: true
  validates :email, format: { with: /\A[^@]+@[^@]+\z/ }
  validates :phone_number, format: { with: /\d{10}/ }, allow_blank: true
  validates :full_name, length: { maximum: 50 }

  delegate :full_name, :email, to: :user, prefix: true, allow_nil: true

  def full_name
    user_full_name || @full_name
  end

  def email
    user_email || @email
  end
end

app/models/song.rb
class Song < ActiveRecord::Base
  include PgSearch

  belongs_to :user

  validates :title, :lyrics, :artist, presence: true
  validates :title, :artist, length: { maximum: 255 }
  validates :rating,
    inclusion: { in: 0..10, message: "Rating value must be between 0 and 10" },
    allow_nil: true

  scope :ordered, -> { order(created_at: :desc) }
  scope :single, -> { where(single: true) }
  scope :with_release_date, -> (date) { where(release_date: date) }
  scope :with_rating, -> (rating) { where(rating: rating) }

  attachment :image, type: :image

  %w(title lyrics artist).each do |column|
    pg_search_scope "with_#{column}", against: column, using: { tsearch: { prefix: true } }
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable, :confirmable,
    :recoverable, :rememberable, :trackable, :validatable

  has_many :songs, dependent: :destroy

  validates :full_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authentication
  include Authorization

  protect_from_forgery with: :exception
  responders :flash

  decent_configuration do
    strategy DecentExposure::StrongParametersStrategy
  end
end

app/controllers/concerns/authentication.rb
module Authentication
  extend ActiveSupport::Concern

  included do
    helper do
      def current_user
        super.decorate if user_signed_in?
      end
    end
  end

  private

  def devise_parameter_sanitizer
    if resource_class == User
      User::ParameterSanitizer.new(User, :user, params)
    else
      super
    end
  end
end

app/controllers/concerns/authorization.rb
module Authorization
  extend ActiveSupport::Concern

  included do
    include Pundit
    rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  end

  private

  def user_not_authorized
    redirect_to(root_path)
  end
end

app/controllers/contact_us_controller.rb
class ContactUsController < ApplicationController
  respond_to :html

  def new
    @form = ContactUsForm.new(user: current_user)
  end

  def create
    @form = ContactUsForm.new(form_params)
    SendContactUsMessage.call(form: @form)

    respond_with @form, location: contact_us_path
  end

  private

  def form_params
    params.require(:contact_us_form).permit(:full_name, :email, :phone_number, :text)
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def show
    songs = SearchSongs
      .call(params: params[:search])
      .songs
      .includes(:user)
      .decorate

    render partial: "songs/songs_list", locals: { songs: songs }
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  respond_to :html

  before_action :authenticate_user!, except: %i(index show)
  before_action :authorize_resource, only: %i(edit update destroy)

  expose_decorated(:songs) { |default| default.ordered }
  expose_decorated(:song, attributes: :song_params)
  expose(:decorated_song) { song.decorate }

  def index
  end

  def new
  end

  def create
    CreateSong.call(song: song, current_user: current_user)
    respond_with song, location: root_path
  end

  def show
  end

  def edit
  end

  def update
    UpdateSong.call(song: song)
    respond_with song
  end

  def destroy
    DestroySong.call(song: song)
    respond_with song, location: root_path
  end

  private

  def song_params
    params.require(:song).permit(
      :title,
      :artist,
      :lyrics,
      :single,
      :rating,
      :release_date,
      :image
    )
  end

  def authorize_resource
    authorize song, :manage?
  end
end

app/views/application/_messages.html.slim
- flash.each do |type, content|
  div(data-alert class="alert-box #{type}")
    = content
    a.close &times;

app/views/application/_navigation.html.slim
nav.top-bar( data-topbar )

  ul.title-area
    li.name
      h1 = link_to "December PDP example site", root_path
    li.toggle-topbar
      a(href="#")
        i.fi-list

  section.top-bar-section
    = render "navigation_main"
    = render "navigation_user"

app/views/application/_navigation_main.html.slim
ul.left
  - if user_signed_in?
    = active_link_to "Home", root_path, active: :exclusive, wrap_tag: :li
  = active_link_to "Add new song", new_song_path, active: :exclusive, wrap_tag: :li
  = active_link_to "Contact Us", contact_us_path, active: :exclusive, wrap_tag: :li

app/views/application/_navigation_user.html.slim
ul.right
  - if user_signed_in?
    li.has-dropdown
      a.user-dropdown(href="#") = current_user.full_name_with_email
      ul.dropdown
        new_user_registration_path
        li
          a href = edit_user_registration_path
            | Edit profile
        li
          a href = destroy_user_session_path
            | Sign out
  - else
    = active_link_to "Sign in", new_user_session_path, active: :exclusive, wrap_tag: :li
    = active_link_to "Sign up", new_user_registration_path, active: :exclusive, wrap_tag: :li

app/views/contact_us/new.html.slim
.row
  .columns.small-7.small-centered
    h2 Contact Us

    = simple_form_for @form, url: contact_us_path do |f|
      .row
        .columns.small-12
          = f.input :full_name,
            label: false,
            placeholder: "Full Name",
            autofocus: true,
            input_html: { maxlength: 50 }
      .row
        .columns.small-6
          = f.input :email,
            label: false,
            placeholder: "Email"
        .columns.small-6
          = f.input :phone_number,
            label: false,
            placeholder: "Phone number (format: 1234567890)",
            input_html: { maxlength: 10 }
      .row
        .columns.small-12
          = f.input :text,
            as: :text,
            label: false,
            placeholder: "Tell us about your ideas...",
            input_html: { rows: 6 }
      .row
        .columns.small-12
          = f.button :submit, "Send message"

app/views/layouts/application.html.slim
doctype html

html class="no-js" lang="en"

  head
    meta charset="utf-8"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    meta name="robots" content="NOODP,NOYDIR"

    = metamagic site: "DecemberPDP", title: %i(title site), separator: " - "
    = csrf_meta_tags

    = stylesheet_link_tag :application

    = javascript_include_tag "vendor/modernizr"

    = javascript_tag "window.App = {}"

    == analytics_init if GA.tracker

  body
    #root
      = render "navigation"
      = render "messages"

      = yield

    javascript:
      App.currentUserData = #{raw current_user.to_json};

    = javascript_include_tag :application

app/views/songs/_form.html.slim
= simple_form_for song.object, html: { class: "song_form" } do |f|
  = f.input :title, autofocus: true
  = f.input :artist
  = f.input :lyrics, input_html: { rows: 6 }
  = f.input :single
  = f.input :rating
  = f.input :release_date, as: :string, input_html: { class: "date_picker" }
  = f.input :image, as: :attachment, direct: true
  = f.button :submit, "Save"

app/views/songs/_search_form.html.slim
.row
  .small-8.small-centered.columns
    = form_tag search_path,
      method: :get,
      class: "search_form",
      data: { remote: true, behavior: "fragments" } do

      = fields_for :search do |f|
        .row
          .small-6.columns
            .small-2.columns
              = f.label :title, "Title:", class: "inline left"
            .small-10.columns
              = f.text_field :title
          .small-6.columns
            .small-2.columns
              = f.label :artist, "Artist:", class: "inline left"
            .small-10.columns
              = f.text_field :artist

        .row
          .small-12.columns
            .small-1.columns
              = f.label :lyrics, "Lyrics:", class: "inline left"
            .small-11.columns
              = f.text_field :lyrics

        .row
          .small-3.columns
            .small-4.columns
              = f.label :single, "Single:", class: "inline left"
            .small-8.columns
              .switch.round.small
                = f.check_box :single, {}, true, false
                = f.label :single

          .small-6.columns
            .small-4.columns
              = f.label :release_date, "Release date:", class: "inline left"
            .small-8.columns
              = f.text_field :release_date, class: "date_picker"

          .small-3.columns
            .small-5.columns
              = f.label :rating, "Rating:", class: "inline left"
            .small-7.columns
              = f.number_field :rating, min: 0, max: 10

      .row
        = submit_tag "Search", class: "button tiny secondary"

app/views/songs/_song.html.slim
.song-wrapper
  = link_to song.object, class: "song_card" do
    .song-image
      = image_tag(attachment_url(song, :image, :fill, 400, 400))
    .song-content
      span.song-title = song.title
      span.song-artist = song.artist

      .song-meta
        .song-release_date
          = song.release_date
          br
          span.meta_label Release Date

        .song-rating
          = song.rating
          br
          span.meta_label Rating

        - if song.single?
          span.meta_label Single

app/views/songs/_songs_list.html.slim
.songs data-fragment-id="songs"
  = songs.each_slice(3) do |song1, song2, song3|
    .row
      .small-4.columns
        = render song1
      .small-4.columns
        = render song2 if song2.present?
      .small-4.columns
        = render song3 if song3.present?

  - if songs.empty?
    .row
      .small-3.small-centered.columns
        h1 No results

app/views/songs/edit.html.slim
.row
  .columns.small-8.small-centered
    = render "form", song: song

app/views/songs/index.html.slim
= render "search_form"
= render "songs_list", songs: songs

app/views/songs/new.html.slim
.row
  .columns.small-8.small-centered
    = simple_form_for song.object, html: { class: "song_form" } do |f|
      = f.input :title, autofocus: true
      = f.input :artist
      = f.input :lyrics
      = f.input :single
      = f.input :rating
      = f.input :release_date, as: :string, input_html: { class: "date_picker" }
      = f.input :image, as: :attachment, direct: true
      = f.button :submit, "Save"

app/views/songs/show.html.slim
.row
  .song.columns.small-10.small-centered
    .song-image
      = image_tag(attachment_url(song, :image, :fill, 300, 300))
    h2 = song.title
    h4 = song.artist

    .song-meta
      span.song-release_date
        ' Release date:
        = song.release_date
      span.song-rating
        ' Rating:
        = song.rating
      span.song-added_by
        ' Added by:
        = song.added_by
      - if song.single?
        span.meta_label Single
      br
      - if policy(song.object).manage?
        = link_to "Edit", edit_song_path(song)
        '
        ' |
        = link_to "Delete", song_path(song), method: :delete, data: { confirm: "Are you sure?" }

    .song-lyrics
      - song.lyrics.split("\n").each do |paragraph|
        = paragraph
        br

app/views/users/shared/_links.html.slim
h6 Anything else?
ul.links
  - if controller_name != "sessions"
    li = link_to "Sign in", new_session_path(resource_name)

  - if devise_mapping.registerable? && controller_name != "registrations"
    li = link_to "Create a new account", new_registration_path(resource_name)

  - if devise_mapping.recoverable? && controller_name != "passwords"
    li = link_to "Forgot your password?", new_password_path(resource_name)

  - if devise_mapping.confirmable? && controller_name != "confirmations"
    li = link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name)

  - if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != "unlocks"
    li = link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name)

  - if devise_mapping.omniauthable?
    - resource_class.omniauth_providers.each do |provider|
      li = link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider)